CREATE TABLE USERTYPE(ID INT PRIMARY KEY IDENTITY(1,1),USER_TYPE VARCHAR(30));
INSERT INTO USERTYPE(USER_TYPE) VALUES ('ADMIN')
INSERT INTO USERTYPE(USER_TYPE) VALUES ('USER')
SELECT * FROM USERTYPE
DROP TABLE CUSTOMERDET;
CREATE TABLE CUSTOMERDET(ID INT PRIMARY KEY IDENTITY(1,1),NAME VARCHAR(30),EMAIL_ID VARCHAR(30),ADDRESS VARCHAR(30),PHONE_NUMBER VARCHAR(20))
CREATE TABLE LOGIN(ID INT PRIMARY KEY IDENTITY(1,1),USER_NAME VARCHAR(30),PASSWORD VARCHAR(20),USERTYPE_ID int FOREIGN KEY REFERENCES USERTYPE(ID));
SELECT * FROM CUSTOMERDET
SELECT * FROM LOGIN
INSERT INTO LOGIN(USER_NAME,PASSWORD,USERTYPE_ID) VALUES ('ADMIN',123456,1)
CREATE TABLE MENU(ID INT PRIMARY KEY IDENTITY(1,1),ITEM_NAME VARCHAR(30),PRICE VARCHAR(20))
SELECT * FROM MENU
INSERT INTO MENU(ITEM_NAME,PRICE) VALUES ('BURGER','150')
INSERT INTO MENU(ITEM_NAME,PRICE) VALUES ('PIZZA','350')
INSERT INTO MENU(ITEM_NAME,PRICE) VALUES ('SANDWICH','450')
CREATE TABLE USER_ORDER(ID INT PRIMARY KEY IDENTITY(1,1),ITEM_ID VARCHAR(20),QUANTITY INT,ITEM_PRICE VARCHAR(20),ITEM_ACTPRICE VARCHAR(20))
SELECT * FROM USER_ORDER
DROP TABLE USER_ORDER;
DELETE FROM LOGIN WHERE ID=3
